spring:
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    couchbase:
      bucket-name: ${BUCKET_NAME}
  servlet:
    multipart:
      max-file-size: 10GB

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

base:
  url: https://${NGROK_ID}.ngrok-free.app/